[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20" 

[build.processing]
  publish = "build"
  functions = "functions"  
  cache = true

[build.cache]
  paths = ["node_modules"]  